In [1]:
import numpy as np

In [2]:
# 1D array
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Array of zeros
zeros = np.zeros((2, 3))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((3, 2))
print("Ones Array:\n", ones)

# Array with a range of values
range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)

# Array with equally spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_arr)

# Random array
random_arr = np.random.rand(3, 3)  # Uniform distribution
print("Random Array:\n", random_arr)

1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Random Array:
 [[0.49828296 0.04609717 0.89824157]
 [0.69802518 0.42259594 0.68183439]
 [0.72013631 0.53705097 0.18712691]]


In [3]:
# In a numpy array, all the elements must be homogenous (of the same data type)
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # Dimensions
print("Size:", arr.size)  # Total number of elements
print("Data Type:", arr.dtype)  # Type of elements
print("Number of Dimensions:", arr.ndim)  # Number of dimensions

Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, Column 1

# Slicing
print("First row:", arr[0, :])  # All columns of the first row
print("First column:", arr[:, 0])  # All rows of the first column
print("Subarray:\n", arr[0:2, 1:3])  # Rows 0-1 and Columns 1-2

Element at [0, 1]: 2
First row: [1 2 3]
First column: [1 4]
Subarray:
 [[2 3]
 [5 6]]


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

# Broadcasting
scalar = 2
print("Multiply by scalar:", arr1 * scalar)

# Mathematical functions
print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Multiply by scalar: [2 4 6]
Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape
reshaped = arr.reshape((3, 2))
print("Reshaped Array:\n", reshaped)

# Transpose
transposed = arr.T
print("Transposed Array:\n", transposed)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking
stacked = np.vstack((arr1, arr2))  # Vertical stack
print("Stacked Vertically:\n", stacked)

hstacked = np.hstack((arr1, arr2))  # Horizontal stack
print("Stacked Horizontally:", hstacked)

# Splitting
split = np.split(arr2, 3)  # Split into 3 parts
print("Split Array:", split)

Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally: [1 2 3 4 5 6]
Split Array: [array([4]), array([5]), array([6])]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean indexing
even = arr[arr % 2 == 0]
print("Even Numbers:", even)
# Masking is a common technique used
print("Masking:", arr % 2 == 0)

# Filtering
filtered = arr[arr > 3]
print("Numbers greater than 3:", filtered)

Even Numbers: [2 4 6]
Masking: [False  True False  True False  True]
Numbers greater than 3: [4 5 6]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Standard Deviation: 1.707825127659933


###Asignments


In [13]:
arr = np.random.rand(3, 6)

add_row = np.array([0, 0, 2, 4, 5, 3])
arr_added = arr + add_row

reshaped = arr_added.reshape(9, 2)

transposed = reshaped.T

mean_val = transposed.mean()

locations = np.where(transposed > mean_val)
print("arr_added:",arr_added)
print("Final transposed array:\n", transposed)
print("\nMean of array:", mean_val)
print("\nLocations where elements > mean:", locations)

arr_added: [[0.84070036 0.68826349 2.77850404 4.46661876 5.10353637 3.65738358]
 [0.88835638 0.55048979 2.77584344 4.73218247 5.04281456 3.33156947]
 [0.46583727 0.71952105 2.33972433 4.61560423 5.38004986 3.69911503]]
Final transposed array:
 [[0.84070036 2.77850404 5.10353637 0.88835638 2.77584344 5.04281456
  0.46583727 2.33972433 5.38004986]
 [0.68826349 4.46661876 3.65738358 0.55048979 4.73218247 3.33156947
  0.71952105 4.61560423 3.69911503]]

Mean of array: 2.8931174710757297

Locations where elements > mean: (array([0, 0, 0, 1, 1, 1, 1, 1, 1]), array([2, 5, 8, 1, 2, 4, 5, 7, 8]))


In [14]:
data = np.random.poisson(lam=5, size=20)

mean_val = np.mean(data)
std_val = np.std(data)

normalized_data = (data - mean_val) / std_val

print("Original data:", data)
print("Mean:", mean_val)
print("Standard Deviation:", std_val)
print("Centered & Normalized data:", normalized_data)

Original data: [7 6 4 6 5 4 4 6 1 5 5 4 5 5 6 3 5 7 5 5]
Mean: 4.9
Standard Deviation: 1.3379088160259651
Centered & Normalized data: [ 1.56961369  0.8221786  -0.67269158  0.8221786   0.07474351 -0.67269158
 -0.67269158  0.8221786  -2.91499686  0.07474351  0.07474351 -0.67269158
  0.07474351  0.07474351  0.8221786  -1.42012668  0.07474351  1.56961369
  0.07474351  0.07474351]
